on:
  issues:
    types: [created]
  issue_comment:
    types: [created]
  pull_request:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  debug-actions-mention-to-slack:
    runs-on: ubuntu-latest
    name: Debug abeyuya/actions-mention-to-slack
    steps:
      - name: Run
        id: hello
        uses: abeyuya/actions-mention-to-slack@v1
        with:
          who-to-greet: "Mona the Octocat"
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
