on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
  pull_request:
    types: [opened]
  pull_request_review_comment:
    types: [created]

jobs:
  debug-actions-mention-to-slack:
    runs-on: ubuntu-latest
    name: Debug abeyuya/actions-mention-to-slack
    steps:
      - name: Run
        uses: abeyuya/actions-mention-to-slack@v1.3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
