on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [opened, edited, review_requested]
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
    types: [created, edited]

jobs:
  debug-actions-mention-to-slack:
    runs-on: ubuntu-latest
    name: Debug abeyuya/actions-mention-to-slack
    steps:
      - name: Run
        uses: abeyuya/actions-mention-to-slack@b08fc63141c807526a65f3bce92633d2cf8ed132
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          bot-name: "github-actions-test"
          run-id: ${{ github.run_id }}
